#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : vim-fugitive
Version  : 3.2
Release  : 5
URL      : https://github.com/tpope/vim-fugitive/archive/v3.2/vim-fugitive-3.2.tar.gz
Source0  : https://github.com/tpope/vim-fugitive/archive/v3.2/vim-fugitive-3.2.tar.gz
Summary  : Git wrapper so awesome, it should be illegal
Group    : Development/Tools
License  : Vim
Requires: vim-fugitive-data = %{version}-%{release}
Patch1: build.patch

%description
No detailed description available

%package data
Summary: data components for the vim-fugitive package.
Group: Data

%description data
data components for the vim-fugitive package.


%prep
%setup -q -n vim-fugitive-3.2
cd %{_builddir}/vim-fugitive-3.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579630761
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1579630761
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/vim/vim82/autoload/fugitive.vim
/usr/share/vim/vim82/ftdetect/fugitive.vim
/usr/share/vim/vim82/plugin/fugitive.vim
