#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : vim-fugitive
Version  : 3.7
Release  : 11
URL      : https://github.com/tpope/vim-fugitive/archive/v3.7/vim-fugitive-3.7.tar.gz
Source0  : https://github.com/tpope/vim-fugitive/archive/v3.7/vim-fugitive-3.7.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Vim
Requires: vim-fugitive-data = %{version}-%{release}
Patch1: 0001-Add-a-makefile.patch

%description
No detailed description available

%package data
Summary: data components for the vim-fugitive package.
Group: Data

%description data
data components for the vim-fugitive package.


%prep
%setup -q -n vim-fugitive-3.7
cd %{_builddir}/vim-fugitive-3.7
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1654614001
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1654614001
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/vim/vimfiles/autoload/fugitive.vim
/usr/share/vim/vimfiles/ftdetect/fugitive.vim
/usr/share/vim/vimfiles/plugin/fugitive.vim
